// Shared export helpers — used by every CSV download and the print/PDF
// renderer so headers stay consistent across the app.
//
// The school's identity is read from app_settings.trust (Trust identity
// section in Settings). Falls back to bundled defaults so the app still
// produces sensible exports on a fresh install with no settings written
// yet.

const FALLBACK_SCHOOL = {
  name: "Sanfort International School",
  trustName: "Sanvi Educational and Charitable Trust",
  regNo: null,
  pan80g: null,
  contact: null,
  brand: "Vidyalaya360",
};

// Resolve the school identity from `E.SETTINGS` (or any plain settings
// object). Always returns a fully-populated object — missing keys fall
// back to the bundled defaults above so callers never have to null-check.
export function resolveSchool(settings) {
  const trust = (settings && settings.trust) || {};
  return {
    name:      trust.name      || FALLBACK_SCHOOL.name,
    trustName: trust.trustName || trust.name || FALLBACK_SCHOOL.trustName,
    regNo:     trust.regNo     || FALLBACK_SCHOOL.regNo,
    pan80g:    trust.pan80g    || FALLBACK_SCHOOL.pan80g,
    contact:   trust.contact   || FALLBACK_SCHOOL.contact,
    brand:     FALLBACK_SCHOOL.brand,
  };
}

// Build the standard 7–10 line CSV preamble that every export across the
// app shares. Returned as an array of `# ...` comment lines so callers
// can prepend it before their own header row + data.
//
// Usage:
//   const csv = [
//     ...csvHeaderLines("Fee collection report", { school, dateRange: "Apr 2026 → Apr 2026", actor: "Rashmi Iyer", recordCount: 42 }),
//     "Class,Student,Amount,Status",
//     ...rows.map((r) => `${r.cls},"${r.name}",${r.amount},${r.status}`),
//   ].join("\n");
export function csvHeaderLines(reportTitle, opts = {}) {
  const school   = resolveSchool(opts.settings || opts.school ? { trust: opts.school || (opts.settings && opts.settings.trust) } : null);
  const lines = [];
  // School identity block.
  lines.push(`# ${school.name}`);
  if (school.trustName && school.trustName !== school.name) {
    lines.push(`# Run by ${school.trustName}`);
  }
  if (school.regNo)   lines.push(`# Reg No: ${school.regNo}`);
  if (school.pan80g)  lines.push(`# PAN / 80G: ${school.pan80g}`);
  if (school.contact) lines.push(`# Contact: ${school.contact}`);
  // Report metadata.
  lines.push(`#`);
  lines.push(`# Report: ${reportTitle}`);
  if (opts.dateRange) lines.push(`# Date range: ${opts.dateRange}`);
  if (opts.recordCount != null) {
    lines.push(`# Records: ${opts.recordCount}`);
  }
  lines.push(`# Generated: ${new Date().toLocaleString("en-IN")}`);
  if (opts.actor) lines.push(`# Generated by: ${opts.actor}`);
  lines.push(`# Powered by ${school.brand}`);
  lines.push(`#`); // blank separator before the data header
  return lines;
}

// Convenience: trigger a browser download for the given CSV string.
// Centralised so every screen names and dates the file the same way.
export function downloadCsv({ filename, csv }) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename || `report-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ---------------------------------------------------------------------------
// downloadPdf({ title, columns, rows, school, actor, dateRange, summary,
//               filename, orientation, subtitle })
//
// Generates a real PDF file client-side using jsPDF + autoTable and triggers
// a direct download (no print dialog). The layout matches the previous
// HTML/print version: branded header, metadata grid, summary chips, aligned
// data table with navy header + zebra rows, page-numbered footer.
//
// `columns` is an array of { key, label, align?: "left"|"right"|"center",
// width?: number-in-mm, format?: (v, row) => string }. Rows are plain objects
// keyed by column.key.
//
// `summary` is optional — array of { label, value } chips shown above the table.
// `orientation` defaults to "portrait"; pass "landscape" for wide tables.
// ---------------------------------------------------------------------------
export async function downloadPdf({
  title,
  subtitle,
  columns = [],
  rows = [],
  school,
  actor,
  dateRange,
  summary,
  filename,
  orientation = "portrait",
} = {}) {
  if (typeof window === "undefined") return;

  // Lazy-load so the PDF chunk only ships when an admin actually clicks
  // Export PDF.
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableMod.default || autoTableMod;

  const s = resolveSchool({ trust: school });

  // Theme colours — keep these in sync with the on-screen brand.
  const NAVY   = [31, 63, 139];
  const ORANGE = [232, 83, 14];
  const INK    = [26, 26, 26];
  const GREY   = [120, 120, 120];
  const RULE   = [236, 232, 216];
  const SOFT   = [250, 248, 244];
  const ZEBRA  = [251, 249, 244];

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 12; // page margin in mm

  const generated = new Date().toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  // jsPDF's built-in Helvetica/Courier fonts use WinAnsi encoding, which
  // does not include the rupee sign (₹, U+20B9) or many other Unicode
  // glyphs. Without this sanitisation those chars render as garbage like
  // "¹&6&4". Strip the rupee symbol (the column header already says
  // "Amount") and replace narrow no-break spaces from `toLocaleString`.
  const safe = (v) => String(v ?? "")
    .replace(/₹/g, "Rs ")
    .replace(/ | /g, " ");

  // Try to fetch the logo as a data URL so jsPDF can embed it. If the load
  // fails (404 / CORS), we skip the image and shift the text left.
  const logoData = await loadLogoDataUrl("/logo.png");

  let y = M;

  // ---------- Header band ----------
  if (logoData) {
    doc.addImage(logoData, "PNG", M, y, 16, 16, undefined, "FAST");
  }
  const textX = logoData ? M + 20 : M;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  // Split the school name so we can render the last word in orange.
  const schoolName = s.name || "School";
  const parts = schoolName.split(/\s+/);
  if (parts.length >= 2) {
    const accent = parts.pop();
    const main   = parts.join(" ") + " ";
    doc.setTextColor(...NAVY);
    doc.text(main, textX, y + 6);
    const mainW = doc.getTextWidth(main);
    doc.setTextColor(...ORANGE);
    doc.text(accent, textX + mainW, y + 6);
  } else {
    doc.setTextColor(...NAVY);
    doc.text(schoolName, textX, y + 6);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text(safe(String(s.trustName || "").toUpperCase()), textX, y + 11);
  const idMeta = [
    s.regNo   ? `Reg No: ${s.regNo}`   : null,
    s.pan80g  ? `PAN/80G: ${s.pan80g}` : null,
    s.contact ? `${s.contact}`         : null,
  ].filter(Boolean).join("  ·  ");
  if (idMeta) {
    doc.setFontSize(7.5);
    doc.text(safe(idMeta), textX, y + 15);
  }

  // Generated stamp on the right with orange accent bar.
  doc.setDrawColor(...ORANGE);
  doc.setLineWidth(1.2);
  const stampX = W - M - 50;
  doc.line(stampX, y + 1, stampX, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text("Generated", stampX + 3, y + 5);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...INK);
  doc.text(generated, stampX + 3, y + 10);

  // Navy underline beneath the header band.
  y += 20;
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.6);
  doc.line(M, y, W - M, y);
  y += 6;

  // ---------- Title + subtitle ----------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  doc.text(title || "Report", M, y + 1);
  y += 5;
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...GREY);
    doc.text(subtitle, M, y + 2);
    y += 5;
  }
  y += 3;

  // ---------- Metadata line (no boxes) ----------
  // Single inline line with key/value pairs separated by middots. Keeps
  // the report context (date range, who ran it, record count) without
  // the heavy bordered cards.
  const metaBits = [
    `Date: ${dateRange || "All time"}`,
    `Generated by ${actor || "System"}`,
    `${rows.length.toLocaleString("en-IN")} record${rows.length === 1 ? "" : "s"}`,
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GREY);
  doc.text(safe(metaBits.join("   ·   ")), M, y + 2);
  y += 7;

  // ---------- Summary line (optional, no boxes) ----------
  if (Array.isArray(summary) && summary.length) {
    const bits = summary.map((c) => `${c.label}: ${safe(c.value)}`);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...NAVY);
    doc.text(bits.join("   ·   "), M, y + 2);
    y += 7;
  }

  // ---------- Data table (autoTable) ----------
  const head = [columns.map((c) => safe(c.label || ""))];
  const body = rows.length === 0
    ? [[{ content: "No records to show.", colSpan: columns.length, styles: { halign: "center", textColor: GREY, fontStyle: "italic", cellPadding: 8 } }]]
    : rows.map((row) => columns.map((c) => {
        const raw = row[c.key];
        const formatted = c.format ? c.format(raw, row) : (raw == null ? "" : String(raw));
        return safe(formatted);
      }));

  autoTable(doc, {
    startY: y,
    head, body,
    margin: { left: M, right: M },
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 8.5,
      cellPadding: 2,
      lineColor: RULE,
      lineWidth: 0.15,
      textColor: INK,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: NAVY,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 7.5,
      cellPadding: 2.5,
      halign: "left",
    },
    alternateRowStyles: { fillColor: ZEBRA },
    columnStyles: columns.reduce((acc, c, i) => {
      const styles = {};
      if (c.align)  styles.halign = c.align;
      if (c.width)  styles.cellWidth = typeof c.width === "number" ? c.width : undefined;
      acc[i] = styles;
      return acc;
    }, {}),
    didDrawPage: () => {
      // Page-numbered footer painted on every page.
      const pageNum = doc.internal.getCurrentPageInfo().pageNumber;
      const totalPages = doc.internal.getNumberOfPages();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...GREY);
      const footY = H - 8;
      doc.text(
        `${s.name} · Page ${pageNum} of ${totalPages}`,
        W / 2, footY, { align: "center" }
      );
      doc.setTextColor(...NAVY);
      doc.text(`${s.brand} · auto-generated`, M, footY);
      doc.setTextColor(...GREY);
      doc.text(generated, W - M, footY, { align: "right" });
    },
  });

  // Trigger a real file download — no dialog.
  const docTitle = filename || `${(title || "report").toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}`;
  doc.save(`${docTitle}.pdf`);
  return true;
}

// Fetches an image and converts to a data URL so jsPDF can embed it.
// Returns null if the image isn't reachable (we just skip the logo then).
function loadLogoDataUrl(src) {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        try {
          const c = document.createElement("canvas");
          c.width = img.naturalWidth || 128;
          c.height = img.naturalHeight || 128;
          const ctx = c.getContext("2d");
          ctx.drawImage(img, 0, 0);
          resolve(c.toDataURL("image/png"));
        } catch { resolve(null); }
      };
      img.onerror = () => resolve(null);
      img.src = src;
    } catch { resolve(null); }
  });
}

// =====================================================================
// SCALE — student report card PDF.
// Custom layout (not the generic table renderer above) — branded
// header, identity row, four domain bars, composite block, per-domain
// narrative paragraphs, priority focus list, teacher observation
// space, three signature blocks.
// =====================================================================
//
// payload = {
//   school, actor,
//   student: { name, cls, roll, term },
//   composite,                             // 0..100 or null
//   compositeBand,                         // string, e.g. "Progressing well"
//   domains,                               // [{ key, label, score, bandLabel, color, narrative }]
//   priorityFocus,                         // [{ indicator, score, action }]
//   observation,                           // free-text from teacher (optional)
//   filename,
// }
export async function downloadScaleReportPdf(payload = {}) {
  if (typeof window === "undefined") return;
  const [{ default: jsPDF }] = await Promise.all([import("jspdf")]);

  const s = resolveSchool({ trust: payload.school });

  const NAVY   = [31, 63, 139];
  const ORANGE = [232, 83, 14];
  const INK    = [26, 26, 26];
  const INK2   = [60, 60, 60];
  const GREY   = [120, 120, 120];
  const SOFT   = [250, 248, 244];
  const RULE   = [220, 215, 200];

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 12;
  const generated = new Date().toLocaleString("en-IN", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });
  const logoData = await loadLogoDataUrl("/logo.png");
  let y = M;

  // -------- Header band --------
  if (logoData) doc.addImage(logoData, "PNG", M, y, 16, 16, undefined, "FAST");
  const textX = logoData ? M + 20 : M;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  const parts = String(s.name || "School").split(/\s+/);
  if (parts.length >= 2) {
    const accent = parts.pop();
    const main   = parts.join(" ") + " ";
    doc.setTextColor(...NAVY); doc.text(main, textX, y + 6);
    const mainW = doc.getTextWidth(main);
    doc.setTextColor(...ORANGE); doc.text(accent, textX + mainW, y + 6);
  } else {
    doc.setTextColor(...NAVY); doc.text(parts[0], textX, y + 6);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8); doc.setTextColor(...GREY);
  doc.text(String(s.trustName || "").toUpperCase(), textX, y + 11);
  const idMeta = [s.regNo && `Reg No: ${s.regNo}`, s.pan80g && `PAN/80G: ${s.pan80g}`, s.contact].filter(Boolean).join("  ·  ");
  if (idMeta) { doc.setFontSize(7.5); doc.text(idMeta, textX, y + 15); }

  // SCALE Report stamp on the right
  doc.setDrawColor(...ORANGE); doc.setLineWidth(1.2);
  const stampX = W - M - 50;
  doc.line(stampX, y + 1, stampX, y + 14);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(...GREY);
  doc.text("SCALE Report", stampX + 3, y + 5);
  doc.setFont("helvetica", "bold"); doc.setFontSize(9.5); doc.setTextColor(...INK);
  doc.text(`Generated ${generated}`, stampX + 3, y + 10);

  y += 20;
  doc.setDrawColor(...NAVY); doc.setLineWidth(0.6); doc.line(M, y, W - M, y);
  y += 7;

  // -------- Student identity --------
  const stu = payload.student || {};
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...INK);
  doc.text(stu.name || "—", M, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(...INK2);
  const sub = [stu.cls && `Class ${stu.cls}`, stu.roll && `Roll ${stu.roll}`, stu.term && `Term ${stu.term}`].filter(Boolean).join("  ·  ");
  if (sub) { y += 5; doc.text(sub, M, y); }
  y += 8;

  // -------- Domain score bars --------
  const domains = payload.domains || [];
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...NAVY);
  doc.text("DOMAIN SCORES", M, y);
  y += 5;
  const barW = W - M * 2;
  const labelColW = 38;
  for (const d of domains) {
    // Label
    doc.setFont("helvetica", "bold"); doc.setFontSize(9.5); doc.setTextColor(...INK);
    doc.text(d.label || d.key, M, y + 4);
    // Track
    doc.setFillColor(...SOFT);
    doc.rect(M + labelColW, y, barW - labelColW - 28, 5, "F");
    // Fill
    const score = d.score == null ? 0 : Math.max(0, Math.min(100, d.score));
    if (score > 0) {
      const rgb = hexToRgb(d.color) || NAVY;
      doc.setFillColor(...rgb);
      doc.rect(M + labelColW, y, ((barW - labelColW - 28) * score) / 100, 5, "F");
    }
    // Score + band on the right
    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...INK);
    doc.text(d.score == null ? "—" : `${d.score}`, W - M - 24, y + 4);
    doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(...GREY);
    doc.text(d.bandLabel || "", W - M - 18, y + 4);
    y += 8;
  }
  y += 2;

  // -------- Composite --------
  doc.setDrawColor(...RULE); doc.setLineWidth(0.3); doc.line(M, y, W - M, y);
  y += 6;
  doc.setFillColor(...SOFT);
  doc.roundedRect(M, y, W - M * 2, 14, 1.6, 1.6, "F");
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(...GREY);
  doc.text("SCALE COMPOSITE SCORE", M + 4, y + 5);
  doc.setFont("helvetica", "bold"); doc.setFontSize(20); doc.setTextColor(...NAVY);
  const compositeText = (payload.composite == null ? "—" : `${payload.composite}`) + " / 100";
  doc.text(compositeText, M + 4, y + 12);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...ORANGE);
  doc.text(payload.compositeBand || "", W - M - 4 - doc.getTextWidth(payload.compositeBand || ""), y + 9);
  y += 18;

  // -------- Per-domain narratives --------
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...NAVY);
  doc.text("DOMAIN OBSERVATIONS", M, y);
  y += 5;
  for (const d of domains) {
    if (y > H - 60) { doc.addPage(); y = M; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(9.5); doc.setTextColor(...INK);
    const head = `${d.label} · ${d.score == null ? "—" : d.score}${d.bandLabel ? ` · ${d.bandLabel}` : ""}`;
    doc.text(head, M, y);
    y += 4;
    doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...INK2);
    const wrapped = doc.splitTextToSize(d.narrative || "—", W - M * 2);
    doc.text(wrapped, M, y + 4);
    y += 4 + wrapped.length * 4 + 2;
  }
  y += 2;

  // -------- Priority focus --------
  if (Array.isArray(payload.priorityFocus) && payload.priorityFocus.length > 0) {
    if (y > H - 70) { doc.addPage(); y = M; }
    doc.setFillColor(255, 247, 230);
    doc.roundedRect(M, y, W - M * 2, 6 + payload.priorityFocus.length * 7, 1.6, 1.6, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(...ORANGE);
    doc.text("PRIORITY FOCUS — NEXT TERM", M + 3, y + 5);
    let py = y + 10;
    payload.priorityFocus.forEach((p, i) => {
      doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(...INK);
      const action = doc.splitTextToSize(`${i + 1}. ${p.action}`, W - M * 2 - 6);
      doc.text(action, M + 3, py);
      py += action.length * 4;
    });
    y = py + 6;
  }

  // -------- Teacher observation --------
  if (y > H - 50) { doc.addPage(); y = M; }
  doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(...NAVY);
  doc.text("TEACHER OBSERVATION", M, y);
  y += 4;
  if (payload.observation) {
    doc.setFont("helvetica", "italic"); doc.setFontSize(9); doc.setTextColor(...INK2);
    const wrapped = doc.splitTextToSize(`"${payload.observation}"`, W - M * 2);
    doc.text(wrapped, M, y + 4);
    y += 4 + wrapped.length * 4 + 4;
  } else {
    // Three handwriting lines for an in-person teacher write-in.
    for (let i = 0; i < 3; i++) {
      doc.setDrawColor(...RULE); doc.setLineWidth(0.2);
      doc.line(M, y + 4 + i * 5, W - M, y + 4 + i * 5);
    }
    y += 22;
  }

  // -------- Signatures --------
  if (y > H - 30) { doc.addPage(); y = M; }
  y += 6;
  const sigW = (W - M * 2 - 20) / 3;
  ["Class teacher", "Principal / coordinator", "Parent / guardian"].forEach((label, i) => {
    const x = M + i * (sigW + 10);
    doc.setDrawColor(...INK); doc.setLineWidth(0.4);
    doc.line(x, y, x + sigW, y);
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(...GREY);
    doc.text(label, x, y + 4);
  });

  // Footer
  doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(...GREY);
  doc.text(`SCALE — Student Competency and Activity Ledger for Education · ${generated}`, M, H - M);
  if (payload.actor) {
    const actorText = `Generated by ${payload.actor}`;
    doc.text(actorText, W - M - doc.getTextWidth(actorText), H - M);
  }

  const filename = payload.filename || `scale-report-${(stu.name || "student").toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

// "#1f7a3a" → [31, 122, 58]; null on bad input.
function hexToRgb(hex) {
  if (typeof hex !== "string") return null;
  const m = hex.replace("#", "").match(/^([0-9a-f]{6})$/i);
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}
